name: Continuous Integration

on: 
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Python Lint Code Scanning
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: List directory contents
        run: ls -R  # Adiciona uma etapa para listar a estrutura de diretórios

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3